image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      zsh -c '
        set -e
        set +x
        . ~/.zshrc

        printenv

        which python

        export PIP_USER=no

        pip install poetry
        
        poetry install
        poetry run pre-commit run -a
        poetry run pre-commit install
      '

vscode:
  extensions:
    - ms-python.python
    - k--kato.intellij-idea-keybindings
