image:
  file: .gitpod.dockerfile

tasks:
  - init: bash -c 'pip install poetry && poetry install && pytest'
    command: PIP_USER=no pre-commit install


vscode:
  extensions:
    - ms-python.python
    - k--kato.intellij-idea-keybindings
