image:
  file: .gitpod.dockerfile

tasks:
  - init: scripts/init.sh || exit 1

github:
  prebuilds:
    branches: true

vscode:
  extensions:
    - ms-python.python
    - k--kato.intellij-idea-keybindings
    - timonwong.shellcheck
