image:
  file: .gitpod.dockerfile

tasks:
  - init: zsh -c 'pip install poetry && poetry install && pytest && PIP_USER=no pre-commit run -a && pre-commit install'

vscode:
  extensions:
    - ms-python.python
    - k--kato.intellij-idea-keybindings
