image:
  file: .gitpod.dockerfile

tasks:
  - init: zsh -c '. ~/.zshrc; pip install poetry && PIP_USER=no poetry install && PIP_USER=no pre-commit run -a && pre-commit install'

vscode:
  extensions:
    - ms-python.python
    - k--kato.intellij-idea-keybindings
