exclude_patterns:
- .*/**/*
- Library/**/*
- .pytest_cache/**/*
execute:
  cache: /Users/alexremedios/Library/Application Support/nbmake/183a014c-981d-4999-8905-335c2c291fad/cache
  execute_notebooks: cache
