
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='nbmake',
    version='0.0.1',
    description='Pytest plugin for releasing notebooks',
    python_requires='==3.*,>=3.6.1',
    project_urls={"homepage": "https://github.com/treebeardtech/nbmake"},
    author='alex-treebeard',
    author_email='alex@treebeard.io',
    license='Apache-2.0',
    entry_points={"pytest11": ["nbmake = nbmake.pytest_plugin"]},
    packages=['docs._build._page.landing-page.html._static', 'docs._build.html._static'],
    package_dir={"": "src"},
    package_data={"docs._build._page.landing-page.html._static": ["*.css", "*.html", "*.js", "*.png", "*.svg", "css/*.css", "images/*.png", "images/*.svg", "js/*.js", "vendor/fontawesome/5.13.0/*.txt", "vendor/fontawesome/5.13.0/css/*.css", "vendor/fontawesome/5.13.0/webfonts/*.eot", "vendor/fontawesome/5.13.0/webfonts/*.svg", "vendor/fontawesome/5.13.0/webfonts/*.ttf", "vendor/fontawesome/5.13.0/webfonts/*.woff", "vendor/fontawesome/5.13.0/webfonts/*.woff2", "vendor/lato_latin-ext/1.44.1/*.css", "vendor/lato_latin-ext/1.44.1/*.md", "vendor/lato_latin-ext/1.44.1/files/*.woff", "vendor/lato_latin-ext/1.44.1/files/*.woff2", "vendor/open-sans_all/1.44.1/*.css", "vendor/open-sans_all/1.44.1/*.md", "vendor/open-sans_all/1.44.1/files/*.woff", "vendor/open-sans_all/1.44.1/files/*.woff2"], "docs._build.html._static": ["*.css", "*.html", "*.js", "*.png", "*.svg", "css/*.css", "images/*.png", "images/*.svg", "js/*.js", "vendor/fontawesome/5.13.0/*.txt", "vendor/fontawesome/5.13.0/css/*.css", "vendor/fontawesome/5.13.0/webfonts/*.eot", "vendor/fontawesome/5.13.0/webfonts/*.svg", "vendor/fontawesome/5.13.0/webfonts/*.ttf", "vendor/fontawesome/5.13.0/webfonts/*.woff", "vendor/fontawesome/5.13.0/webfonts/*.woff2", "vendor/lato_latin-ext/1.44.1/*.css", "vendor/lato_latin-ext/1.44.1/*.md", "vendor/lato_latin-ext/1.44.1/files/*.woff", "vendor/lato_latin-ext/1.44.1/files/*.woff2", "vendor/open-sans_all/1.44.1/*.css", "vendor/open-sans_all/1.44.1/*.md", "vendor/open-sans_all/1.44.1/files/*.woff", "vendor/open-sans_all/1.44.1/files/*.woff2"]},
    install_requires=['jupyter-book', 'jupyter-cache[cli]==0.*,>=0.4.1', 'pathlib==1.*,>=1.0.1', 'pydantic==1.*,>=1.7.2', 'pytest==6.*,>=6.1.2', 'pyyaml==5.*,>=5.3.1'],
    dependency_links=['git+https://github.com/executablebooks/jupyter-book.git@6c30f55#egg=jupyter-book'],
    extras_require={"dev": ["dephell==0.*,>=0.8.3", "pre-commit==2.*,>=2.8.2", "pytest-cov==2.*,>=2.10.1", "pytest-xdist==2.*,>=2.1.0", "virtualenv==20.*,>=20.1.0"]},
)
