title: "nbmake"
author: nbmake
email: alex@treebeard.io
description: >- # this means to ignore newlines until "baseurl:"
  nbmake example
exclude_patterns:
  - .pytest_cache
  - _build
  # - landing*
  - page1*

execute:
  execute_notebooks: cache
  cache: "_build/cache"
